sudo: required
services:
- docker
language: python
env: ANDROID_BUILDER_IMAGE=lins05/android-sdk:latest
install:
- time docker pull $ANDROID_BUILDER_IMAGE
script:
- docker run -it --rm --name seadoid-builder -v $PWD:$PWD -w $PWD $ANDROID_BUILDER_IMAGE
  ./gradlew clean assembleRelease
before_install:
  # travis ci can only encrypt at most one file, so we have to create a tarball for release.keystore and key.properties
- openssl aes-256-cbc -K $encrypted_fe9440d471e8_key -iv $encrypted_fe9440d471e8_iv
  -in signkeys.tar.gz.enc -out signkeys.tar.gz -d
- tar xf signkeys.tar.gz -C app --strip-components=1
